
name:Deploy to server
on:
  push:
    branches:
      -main
    jobs:
      deploy:
        runs-on:ubuntu-latest
      steps:
        -name:Checkout code
        uses:actions/checkout@v4
        -name:Deploy over SSH
        uses:appleboy/ssh-action@v1.0.0
        with:
          host:${{secrets.SERVER_IP}}
          username:${{secrets.SERVER_USER}}
          key:${{secrets.SSH_KEY}}

script: |
cd /home/evoluzn/SmartAppProject
git pull origin main
source venv/bin/activate
pip install -r requirements.txt
sudo systemctl restart smart_app.service